# config.yaml
run_id: "experiment_name7"
model_name: "gpt-5.1" # gpt-5.1, gpt-4.1, gpt-3.5-turbo
interactive: false
max_refinement_rounds: 30
preserve_artifacts: true
api_key: null

agent_models:
  CODER: 'hf/meta-llama/Meta-Llama-3-8B-Instruct'
  CODER: 'gpt-4.1'
