# config.yaml
run_id: "experiment_name9"
model_name: "gpt-5.1" # gpt-5.1, gpt-4.1, gpt-3.5-turbo
interactive: false
max_refinement_rounds: 30
preserve_artifacts: true
api_key: null

agent_models:
  CODER: 'hf/Qwen/Qwen3-Coder-Next'
  # CODER: 'gpt-4.1'
